# Generated by Django 4.2.7 on 2024-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50, verbose_name='Названия статьи')),
                ('article_text', models.TextField(verbose_name='text articles')),
            ],
        ),
    ]
